version: 2
updates:
  - package-ecosystem: gomod
    directory: /agent
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /app
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
